stages:
  - build
build_project:
  stage: build
  script:
    - xcodebuild -sdk iphonesimulator -scheme GEObfuscationSample -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.2' -enableCodeCoverage YES test CODE_SIGNING_REQUIRED=NO | xcpretty
  tags:
    - ios_9-2
    - xcode_9-2
    - osx_10-13
